name: Build Hali

on:
  pull_request:
    branches:
      - master

jobs:
  lint-checks:
    name: Lint Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "17"

      - name: Run Lint Checks
        run: |
          ./gradlew ktlintCheck

  run-tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "17"

      - name: Run tests
        run: |
          ./gradlew testDebugUnitTest

  build:
    needs:
      - lint-checks
      - run-tests
    name: Assemble Android Apk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "17"

      - name: Build Android App
        run: |
          ./gradlew assembleDebug
